### ISSUE TITLE
Rename applications to websites

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/WebAppMaker#1]
The original intention of this Web site was to create Web applications, hence the name WebAppMaker. But it has grown to be more than that, so it is appropriate that we rename several artifacts that specifically refer to "application" and change their name to "website".

Rename all occurrences of "application" to "website". Here are places I have identified that need to be changed. There might be more places.
- Rename /public/ide/views/application to /public/ide/views/website
- Rename /public/ide/views/application/application.controller.js to /public/ide/views/website/website.controller.js
- Rename /public/ide/views/application/application-_.html to /public/ide/views/website/website-_.html
- Rename /ide/services/application.service.server.js to /ide/services/website.service.server.js
- Rename /ide/models/application/application.model.server.js to /ide/models/website/website.model.server.js

**Comment by anshika1** [comment]
Resolved
