### ISSUE TITLE
Widget Sorting not Working in Mobile View in Chrome

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/WebAppMaker#2]
Steps to reproduce
1. Create a Website
2. Create a Page for the Website
3. Create several widgets in the page
4. Click and drag widgets to reorder. It works
5. Switch browser to mobile preview
6. Click and drag widgets to reorder. It does not work

I had installed jquery.ui.touch-punch.min.js to solve this problem, and I thought I had gotten it to work, but something broke.

**Comment by anshika1** [comment]
Pull Request : https://github.com/jannunzi/WebAppMaker/pull/11
