### ISSUE TITLE
WL-23 - Show Widget Toolbox in Landscape View

### ISSUE THREAD

**Issue by ghost** [jannunzi/WebAppMaker#23]
Create a landscape version of the widget manager interface.
The wireframe is at this link:

https://docs.google.com/presentation/d/1Z8EANDEtCk_i2rre1_9H6QDYPX94e_piuU6e-89uSmI/edit?usp=sharing
1. In portrait, widget list displays list of widgets as currently implemented
2. In landscape, widget list displays list of widgets on the left 2/3, and a widget toolbox on the right 1/3

**Comment by sruthinagalla** [comment]
Hi,
I will be working on this.
-Sruthi
