### ISSUE TITLE
WL-24 - Style Widget Toolbox in Landscape View

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/WebAppMaker#24]
Widget List shows Widget Toolbox in Landscape View

Style Widget Toolbox as shown in wireframes

https://docs.google.com/presentation/d/1Z8EANDEtCk_i2rre1_9H6QDYPX94e_piuU6e-89uSmI/edit?usp=sharing

**Comment by sruthinagalla** [comment]
Hi ! I would like to work on this!

**Comment by sruthinagalla** [comment]
Hi Professor,
I fixed this issue and checked in the code. PFA the screenshot.
![widget](https://cloud.githubusercontent.com/assets/11529819/18029303/0f71366a-6cb2-11e6-9e57-0dd2aa55088b.PNG)
