### ISSUE TITLE
Widgets manager landscape

### ISSUE THREAD

**Issue by ghost** [jannunzi/WebAppMaker#25]
https://docs.google.com/presentation/d/1Z8EANDEtCk_i2rre1_9H6QDYPX94e_piuU6e-89uSmI/edit#slide=id.g115703c8cc_0_0

**Comment by sruthinagalla** [comment]
![widget](https://cloud.githubusercontent.com/assets/11529819/18029296/d0d4c944-6cb1-11e6-8071-189616d28cd8.PNG)
PFA screenshot that meets the requirements of the issue. Code is merged into dev-summer2-2016
