### ISSUE TITLE
developer-edit.view.html form not using proper bootstrap form template

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/WebAppMaker#6]
the form elements in this file are of the form

Usename
<input ng-model="model.developer.username"
       class="form-control"
       placeholder="username"/>

Email
<input ng-model="model.developer.email"
       class="form-control"
       placeholder="email"/>

etc...

Instead they should use

<form>
  <div class="form-group">
    <label for="username">Usename</label>
    <input ng-model="model.developer.username"
    class="form-control" id="username" placeholder="John">
  </div>

  <div class="form-group">
    <label for="email">Email</label>
    <input ng-model="model.developer.email" type="email"
    class="form-control" id="email" placeholder="john@acme.com">
  </div>

etc...

</form>

Please change all the old form elements to use proper bootstrap templates

Do this for all form elements in the following files:

developer-edit.html
developer-new.html
page-edit.html
page-new.html
website-new.html
website-edit.html
widget-edit.html

And any other forms...

**Comment by anshika1** [comment]
Pull Request : https://github.com/jannunzi/WebAppMaker/pull/18

**Comment by anshika1** [comment]
https://github.com/jannunzi/WebAppMaker/commit/736d8d32b238b9552603bd31a66ab2c67e61cdb1
