### ISSUE TITLE
Use DIVs to layout website-list.html instead of TABLE

### ISSUE THREAD

**Issue by jannunzi** [jannunzi/WebAppMaker#7]
Take a look at how website-list.html is implemented compared to page-list.html. Website-list.html uses tables and rows to render a list of websites. page-list.html instead uses DIVs. Refactor website-list.html to be implemented like page-list.html using DIVs instead of tables.

**Comment by anshika1** [comment]
Pull Request : https://github.com/jannunzi/WebAppMaker/pull/10

**Comment by anshika1** [comment]
https://github.com/jannunzi/WebAppMaker/commit/fe904032c7bc0db88eb5bce5852ea0daf808a6f4
